sudo: required
services:
  - docker

before_install:
  - docker build -t renanpapa/docker-react -f Dockerfile.dev .

script:
  - docker run renanpapa/docker-react npm run test -- --coverage

deploy:
  provider: azure_web_apps
  site: https://prmdocker-create922.azurewebsites.net

on:
  branch: master